parameters:
  arch: [UKAN]
  dataset: [roweeder]
  input_channels: [3]
  num_classes: [3]
  input_w: [512]
  input_h: [512]
  input_list: ["128,160,256", "64,80,128", "32,40,64", "16,20,32", "8,10,16", "4,6,8"]
  epochs: [500]
  data_dir: [data/weedmap/UKAN]
  loss: [FocalLoss]
  loss_weights: [True, False]
  batch_size: [2]
  early_stopping: [20]
  optimizer: [Adam]
  lr: [1e-2, 1e-3, 1e-4, 1e-5]
  min_lr: [1e-6]
  weight_decay: [1e-4]
  kan_lr: [1e-2, 1e-3]
  kan_weight_decay: [1e-4]
  scheduler: [ReduceLROnPlateau]
  factor: [0.1]
  output_dir: [outputs]
  no_kan: [False]
  patience: [5]
  deep_supervision: [False]
  dataseed: [2981]
  num_workers: [4]

other_grids:
